spring:
  profiles: default
  data:
    mongodb:
      host: mongo.service.consul
      port: 27017
      database: chatapp
  rabbitmq:
    host: rabbit.service.consul
    port: 5672
server:
  port: 9091
tomcat:
  access-log-enabled: false

---

spring:
  profiles: test
  data:
    mongodb:
      host: mongo.service.consul
      port: 27017
      database: chatapp
  rabbitmq:
    host: rabbit.service.consul
    port: 5672
server:
  port: 9091
