spring:
  profiles.active: default
  data:
    mongodb:
      host: mongo.service.consul
      port: 27017
      database: chatapp
  rabbitmq:
    host: rabbit.service.consul
    port: 5672
server:
  port: 9091

---

spring:
  profiles.active: test
  data:
      mongodb:
        host: localhost
        port: 27017
        database: chatapptest
