spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatapp
  rabbitmq:
    host:
    port: 5672
server:
  port: 9091
logging:
  level:
    ROOT: DEBUG

---

spring:
  profiles: test
  data:
    mongodb:
      host: mongo.service.consul
      port: 27017
      database: chatapp
  rabbitmq:
    host: rabbit.service.consul
    port: 5672
server:
  port: 9091
