spring:
  profiles: default
  data:
    mongodb:
      host: mongo.service.consul
      port: 27017
      database: chatapp
  rabbitmq:
    host: rabbit.service.consul
    port: 5672
server:
  port: ${SPRING_PORT}

---

spring:
  profiles: test
  data:
    mongodb:
      host: mongo.service.consul
      port: 27017
      database: chatapp
  rabbitmq:
    host: rabbit.service.consul
    port: 5672
server:
  port: ${SPRING_PORT}
