FROM dockerfile/java:oracle-java7
MAINTAINER chris@chrisrichardson.net
EXPOSE 8080
CMD java -jar restful-chat-service-0.1.0.jar
ADD build/libs/restful-chat-service-0.1.0.jar /data/restful-chat-service.jar